import { Project, TechFlora, EducationMilestone } from '../types';

export const PERSONAL_INFO = {
  name: "Disha Das",
  kanjiName: "ディシャ・ダス",
  role: "AI Agent Engineer & Full-Stack Creative Builder",
  eyebrow: "AI AGENT ENGINEER • LLM WORKFLOWS • RAG ARCHITECT",
  location: "Duttapukur, West Bengal, India (Kolkata)",
  phone: "+91 9330614416",
  email: "dishadas050@gmail.com",
  github: "https://github.com/disha-das756",
  githubHandle: "github.com/disha-das756",
  linkedin: "https://linkedin.com/in/disha-das-886b10221",
  linkedinHandle: "linkedin.com/in/disha-das-886b10221",
  objective:
    "AI Agent Engineer with hands-on experience building LLM-powered applications using LangChain, RAG pipelines, and AI agents. Strong understanding of agent reasoning (ReAct), tool calling, memory management, and vector databases. Experienced in developing production-style AI APIs using Python and FastAPI.",
  headline: "I build thoughtful AI agents and beautiful software with code.",
  subheadline: "AI Agent Engineer • LangChain & LangGraph Explorer • Creative Builder",
  narrative:
    "I enjoy turning complex ideas into autonomous AI workflows, intelligent document retrieval engines, and software that feels as serene to use as it is robust to run. My craft centers on ReAct reasoning loops, low-latency vector databases, and resilient asynchronous backend architectures."
};

export const PROJECTS: Project[] = [
  {
    id: "docsy-pdf-buddy",
    title: "Docsy — PDF Buddy Agent",
    subtitle: "Chat With Any PDF • RAG + LangGraph",
    category: "rag",
    stage: "In Bloom 🌸",
    image: "/docsy.png",
    shortDesc:
      "A PDF companion that lets you upload a document, read it in a built-in viewer, and chat with it in persistent sessions. Answers are retrieved from a Pinecone vector index and generated by Groq-hosted LLMs.",
    fullDesc:
      "Docsy is a full-stack RAG application. A React + Tailwind frontend pairs a PDF viewer with an AI chat panel and a recent-sessions sidebar. A FastAPI backend ingests PDFs, chunks and embeds them into Pinecone, stores the original file in Supabase, keeps chat history in MongoDB, and answers questions through a LangGraph retrieve ➔ generate workflow.",
    techStack: ["Python", "FastAPI", "LangGraph", "Groq", "Pinecone", "Supabase", "MongoDB", "React", "Tailwind CSS"],
    metrics: [
      { label: "Retrieval", value: "Top-3 Pinecone" },
      { label: "Chunking", value: "800 / 100 overlap" },
      { label: "Memory", value: "Last 10 messages" }
    ],
    problem:
      "Reading long PDFs to find one answer is slow, and generic chatbots can't see your document, so they guess. Users need answers grounded in the file they uploaded, with the file open beside the conversation.",
    architecture:
      "PDF Upload ➔ Recursive Chunking (800 chars, 100 overlap) ➔ Pinecone Embeddings (llama-text-embed-v2) ➔ Vector Index ➔ LangGraph retrieve node (top-3) ➔ generate node (Groq LLM + chat history) ➔ Answer shown in the chat panel.",
    implementation: [
      "Built a FastAPI backend with /upload and /chat endpoints, CORS-locked to the deployed Vercel frontend.",
      "Implemented ingestion with RecursiveCharacterTextSplitter and Pinecone-hosted embeddings, indexing chunks for similarity search.",
      "Modelled the answering flow as a LangGraph StateGraph (query, context, history, answer) with separate retrieve and generate nodes.",
      "Persisted per-session chat history in MongoDB and uploaded source PDFs to Supabase storage so sessions reload with their document.",
      "Built a dark-themed React UI with a session sidebar, embedded PDF viewer, and chat panel."
    ],
    challenges:
      "Keeping the app light enough to deploy while staying grounded: switched to hosted Pinecone embeddings instead of local models, and the generate step declines to answer when retrieval returns nothing relevant.",
    outcomes: [
      "Deployed end-to-end with a Vercel frontend and a FastAPI backend.",
      "Multiple persistent chat sessions, each tied to its own PDF.",
      "Answers are generated from retrieved passages rather than the model's guesswork."
    ],
    githubUrl: "https://github.com/disha-das756/Docsy---Pdf-buddy-agent",
    liveUrl: "https://docsy-pdf-buddy-agent.vercel.app",
    architectureFlow: [
      { step: "PDF Upload", desc: "User uploads a PDF; original is stored in Supabase", type: "input" },
      { step: "Chunk & Embed", desc: "Split into 800-char chunks and embed with Pinecone", type: "tool" },
      { step: "Vector Retrieval", desc: "LangGraph retrieve node fetches the top-3 passages", type: "tool" },
      { step: "Grounded Generation", desc: "Groq LLM answers using context plus recent chat history", type: "reasoning" },
      { step: "Chat Response", desc: "Answer appears beside the PDF viewer and is saved to MongoDB", type: "output" }
    ]
  },
  {
    id: "buymore-fashion-dashboard",
    title: "BuyMore — Fashion Dashboard",
    subtitle: "Full-Stack E-Commerce with an AI Support Bot",
    category: "fullstack",
    stage: "In Bloom 🌸",
    image: "/ecommerce.png",
    shortDesc:
      "A haute-couture storefront with product browsing, favourites, cart, promo codes, an admin analytics dashboard, and a chatbot that answers store and product questions.",
    fullDesc:
      "BuyMore is a full-stack fashion e-commerce app. A React frontend provides the collections grid, category filters, sorting, search, favourites, cart drawer and auth modal. A FastAPI + SQLAlchemy backend exposes modular routers for auth, products, orders, discounts, favourites and chat, and a LangGraph-based chatbot answers support questions from store policies and the live product catalogue.",
    techStack: ["React", "FastAPI", "SQLAlchemy", "LangGraph", "JWT Auth", "PostgreSQL / SQLite", "Pytest"],
    metrics: [
      { label: "API Design", value: "6 Modular Routers" },
      { label: "Auth", value: "JWT + bcrypt" },
      { label: "Support Bot", value: "LangGraph RAG" }
    ],
    problem:
      "Small fashion stores need more than a product grid: shoppers want to filter, save and check out quickly, owners want sales insight, and support questions about shipping, returns and promo codes repeat constantly.",
    architecture:
      "React SPA ➔ REST API (FastAPI routers: auth, products, orders, discounts, favourites, chat) ➔ SQLAlchemy ORM ➔ SQLite/Postgres. Chat requests flow through a LangGraph state graph that classifies the query, retrieves store policies and products, and responds.",
    implementation: [
      "Built the storefront UI: hero banner, category pills, sort control, product cards, detail modal, favourites counter and cart drawer.",
      "Implemented JWT authentication with hashed passwords and a protected current-user dependency.",
      "Created product and category management, order placement, and a promo-code system (e.g. HALF50 for 50% off).",
      "Added an analytics dashboard with revenue trends and category sales breakdown.",
      "Built a floating chatbot widget backed by a LangGraph graph that checks whether a query is in-domain and retrieves from store policies and live product data.",
      "Wrote API tests with pytest and configured CORS for the Vercel deployment."
    ],
    challenges:
      "Keeping the support bot on-topic and accurate: added a domain check node and built its knowledge base from both fixed store policies and live products fetched from the database.",
    outcomes: [
      "Complete shopping flow from browse to favourites, cart and discounted checkout.",
      "Admin-facing analytics alongside product management.",
      "Frontend deployed on Vercel with a separately hosted API."
    ],
    githubUrl: "https://github.com/disha-das756/fashion-dashboard",
    liveUrl: "https://fashion-dashboard-two.vercel.app",
    architectureFlow: [
      { step: "Shopper Interaction", desc: "Browse, search, favourite and add items to the cart", type: "input" },
      { step: "REST API Layer", desc: "FastAPI routers handle auth, products, orders and discounts", type: "tool" },
      { step: "Persistence", desc: "SQLAlchemy models store users, products, orders and favourites", type: "tool" },
      { step: "Support Chatbot", desc: "LangGraph routes in-domain queries through retrieval of policies and products", type: "reasoning" },
      { step: "Checkout & Insights", desc: "Discounted orders placed; analytics dashboard summarises sales", type: "output" }
    ]
  },
  {
    id: "intellitrip-ai-planner",
    title: "IntelliTrip AI — Multi-Agent Travel Planner",
    subtitle: "LangGraph Agent Pipeline with Self-Evaluation",
    category: "agent",
    stage: "In Bloom 🌸",
    image: "/ai_planner.png",
    shortDesc:
      "A team of specialised AI agents that discovers attractions, writes a day-wise itinerary, estimates the budget in INR, scores its own plan, and exports a PDF.",
    fullDesc:
      "IntelliTrip AI is a multi-agent travel planning system orchestrated with LangGraph. Given a starting city, destination, duration, budget level, travel style and interests, a Places agent searches the web, an Itinerary agent (Llama via Groq) drafts the plan, a Budget agent breaks down costs, and an Evaluator agent critiques the result with a quality score. The Streamlit interface shows the plan and evaluation in tabs and offers a downloadable A4 PDF.",
    techStack: ["Python", "LangGraph", "LangChain", "Groq (Llama 3)", "DuckDuckGo Search", "Streamlit", "ReportLab"],
    metrics: [
      { label: "Agents", value: "4 Specialised" },
      { label: "Orchestration", value: "LangGraph State" },
      { label: "Output", value: "Plan + PDF" }
    ],
    problem:
      "Planning a trip means juggling research, scheduling and budgeting across many tabs. A single LLM prompt returns generic, unverified plans with no cost realism and no check on quality.",
    architecture:
      "User Input ➔ Places Agent (DuckDuckGo search) ➔ Itinerary Agent (Llama via Groq) ➔ Budget Agent (INR cost breakdown) ➔ Evaluator Agent (quality score) ➔ PDF Generator ➔ Downloadable plan.",
    implementation: [
      "Designed a LangGraph workflow where each agent reads and writes a shared state, giving clean hand-offs between steps.",
      "Built a Places agent that grounds suggestions in live DuckDuckGo search results for the chosen destination and interests.",
      "Wrote structured prompt templates for itinerary and budget generation, with category-wise costs for travel, stay, food and activities.",
      "Added an Evaluator agent that critiques practicality, coverage and quality and returns an AI score.",
      "Created a Streamlit UI with sidebar info, form inputs, progress feedback, tabbed results and ReportLab PDF export."
    ],
    challenges:
      "Making outputs consistent across agents: solved with shared graph state and prompt files kept separate from code, so each agent receives exactly the context it needs.",
    outcomes: [
      "End-to-end trip plan generated from a single form submission.",
      "Self-critique step surfaces plan quality instead of trusting the first draft.",
      "Deployed live on Streamlit Community Cloud."
    ],
    githubUrl: "https://github.com/disha-das756/Multi-Agent-AI-Travel-Planner",
    liveUrl: "https://multi-agent-ai-travel-planner-c.streamlit.app/",
    architectureFlow: [
      { step: "Trip Requirements", desc: "City, destination, days, budget level, style and interests", type: "input" },
      { step: "Places Agent", desc: "Searches DuckDuckGo for relevant attractions", type: "tool" },
      { step: "Itinerary Agent", desc: "Synthesises results into a day-wise plan with Llama on Groq", type: "reasoning" },
      { step: "Budget & Evaluator Agents", desc: "Estimate costs in INR, then critique and score the plan", type: "reasoning" },
      { step: "Plan + PDF", desc: "Tabbed results in the app and a downloadable A4 guide", type: "output" }
    ]
  }
];

export const TECH_FLORA: TechFlora[] = [
  {
    id: "python",
    name: "Python",
    floraName: "Crimson Sakura Bloom 🌸",
    category: "Languages",
    level: 95,
    iconEmoji: "🌸",
    description: "Core foundation for AI development, object-oriented programming, data structures, and asynchronous architectures.",
    realUsage: "Built production async APIs, LangChain agents, FAISS vector indexers, and custom Pydantic data schemas.",
    codeSnippet: "class ReActAgent:\n    def __init__(self, tools: list[BaseTool]):\n        self.tools = tools"
  },
  {
    id: "langchain",
    name: "LangChain",
    floraName: "Branching Zen Wisteria 🌿",
    category: "AI & LLM",
    level: 92,
    iconEmoji: "🌿",
    description: "LLM application framework for agent reasoning chains, memory buffers, and custom tool binding.",
    realUsage: "Engineered autonomous ReAct agents, document chunking pipelines, and prompt templates with structured output parsing.",
    codeSnippet: "agent = create_react_agent(\n    model=llm,\n    tools=[search_tool],\n    prompt=react_prompt\n)"
  },
  {
    id: "langgraph",
    name: "LangGraph",
    floraName: "Sacred Ginkgo Tree 🎋",
    category: "AI & LLM",
    level: 88,
    iconEmoji: "🎋",
    description: "Multi-agent cyclic graph orchestration with state checkpointing and human-in-the-loop decision boundaries.",
    realUsage: "Built stateful cyclic workflows with conditional edge routing, error recovery loops, and multi-agent coordination.",
    codeSnippet: "workflow = StateGraph(AgentState)\nworkflow.add_node('researcher', call_agent)\nworkflow.add_edge('researcher', 'evaluator')"
  },
  {
    id: "fastapi",
    name: "FastAPI",
    floraName: "Evergreen Mountain Ivy 🍃",
    category: "Frameworks",
    level: 90,
    iconEmoji: "🍃",
    description: "High-performance asynchronous Python web framework for production-grade AI microservices.",
    realUsage: "Developed asynchronous REST endpoints, streaming Server-Sent Events (SSE) for LLM tokens, and Pydantic request models.",
    codeSnippet: "@app.post('/v1/agent/stream')\nasync def stream_agent(query: QueryModel):\n    return StreamingResponse(run_agent(query))"
  },
  {
    id: "faiss",
    name: "FAISS & Embeddings",
    floraName: "Luminous Vector Lantern 🏮",
    category: "Search & Vector",
    level: 89,
    iconEmoji: "🏮",
    description: "Dense vector indexing and similarity search for sub-millisecond document retrieval in RAG systems.",
    realUsage: "Indexed 100k+ embedded text chunks, implemented cosine similarity retrieval with metadata filtering, and prevented hallucinations.",
    codeSnippet: "vectorstore = FAISS.from_documents(\n    documents=chunks,\n    embedding=OpenAIEmbeddings()\n)"
  },
  {
    id: "models",
    name: "OpenAI & Gemini",
    floraName: "Twin Celestial Lotus 🪷",
    category: "AI & LLM",
    level: 92,
    iconEmoji: "🪷",
    description: "Foundation model selection, structured generation, temperature calibration, and system prompt engineering.",
    realUsage: "Configured GPT-4o and Gemini models for complex reasoning, tool calling, document summarization, and extraction.",
    codeSnippet: "llm = ChatOpenAI(\n    model='gpt-4o',\n    temperature=0.2\n)"
  },
  {
    id: "pydantic",
    name: "Pydantic & OOP",
    floraName: "Cedar Bonsai Geometry 🌲",
    category: "Languages",
    level: 93,
    iconEmoji: "🌲",
    description: "Data validation, strict schema enforcement, custom tool schemas, and robust object-oriented system design.",
    realUsage: "Defined structured input/output schemas for LLM tool invocation, runtime validation, and config parsing.",
    codeSnippet: "class SearchInput(BaseModel):\n    query: str = Field(description='Specific topic to search')\n    max_results: int = 5"
  },
  {
    id: "docker-git",
    name: "Git & Docker",
    floraName: "Cedar Container Bento 📦",
    category: "DevOps",
    level: 85,
    iconEmoji: "📦",
    description: "Version control, team collaboration workflows, and containerized deployment environments for AI services.",
    realUsage: "Maintained clean Git commit histories, branch management, Dockerfile builds for Python FastAPI services, and CI/CD pipelines.",
    codeSnippet: "FROM python:3.11-slim\nWORKDIR /app\nRUN pip install -r requirements.txt\nCMD ['uvicorn', 'main:app']"
  }
];

export const EDUCATION_MILESTONES: EducationMilestone[] = [
  {
    year: "2022 — 2025",
    title: "Bachelor of Technology (B.Tech) – Information Technology",
    institution: "MAKAUT / B. P. Poddar Institute of Management and Technology, Kolkata",
    degree: "B.Tech in Information Technology",
    score: "CGPA: 7.0 / 10.0",
    description:
      "Rigorous 4-year undergraduate degree focusing on Object-Oriented Programming, Data Structures & Algorithms, Database Management Systems, Computer Networks, and Artificial Intelligence.",
    highlights: [
      "In-depth coursework in Python, OOP, Algorithm Analysis, and Software Engineering",
      "Specialized in AI/LLM architectures, culminating in end-to-end RAG and ReAct agent capstone projects",
      "Collaborative team development and technical presentations on modern generative AI",
      "Graduating in 2025 with strong foundation ready for high-impact AI/LLM engineering roles"
    ],
    icon: "🌸"
  },
  {
    year: "2023 — 2024",
    title: "RAG & Vector Search Deep Dive",
    institution: "Self-Driven Applied Research & Laboratory Works",
    description:
      "Deep practical study into Retrieval Augmented Generation, chunking strategies, dense embeddings, FAISS vector search, and hallucination reduction.",
    highlights: [
      "Built multi-format PDF parser and semantic chunking engines",
      "Experimented with cosine distance vs Euclidean metrics in vector spaces",
      "Created strict context-grounded prompt architectures to enforce citation integrity"
    ],
    icon: "🏮"
  },
  {
    year: "2024 — Present",
    title: "Autonomous AI Agents & LangGraph Mastery",
    institution: "Specialized AI Engineering & Production API Development",
    description:
      "Dedicated development of autonomous multi-step reasoning agents using LangChain, LangGraph, tool calling, and production-style FastAPI backends.",
    highlights: [
      "Implemented ReAct cognitive reasoning loops with dynamic tool invocation",
      "Engineered cyclic state machine workflows in LangGraph with memory checkpointing",
      "Actively preparing for AI/LLM engineering roles with production-ready codebases"
    ],
    icon: "🌱"
  }
];

export const CAREER_GROWTH_STAGES = [
  { stage: "LEARN", label: "Seedling", desc: "Data structures, OOP, Python algorithms & web fundamentals", icon: "🌱" },
  { stage: "BUILD", label: "Sprout", desc: "FastAPI backends, REST APIs & full-stack integrations", icon: "🌿" },
  { stage: "REASON", label: "Branching", desc: "LangChain, ReAct agents, tool calling & memory loops", icon: "🎋" },
  { stage: "GROUND", label: "Budding", desc: "FAISS vector search, semantic embeddings & RAG pipelines", icon: "🌷" },
  { stage: "BLOOM", label: "Full Blossom", desc: "Production AI Agent Engineering & stateful LangGraph workflows", icon: "🌸" }
];

export const EASTER_EGGS = {
  mascotQuotes: [
    "I'm debugging the agent's memory loop... deep in focus 💻🍵",
    "Zero hallucinations detected in the RAG corpus! 🌸",
    "Matcha fuel +10! Ready for another LangGraph cycle ✨",
    "Did you know? FAISS vector cosine similarity searches happen in under 10 milliseconds! 🏮",
    "Did you check out IntelliTrip AI? Four agents plan your whole trip! 💻",
    "Welcome to my digital garden! May your code compile cleanly and your flowers bloom 🌸"
  ],
  lanternMsg: "A warm lantern light for your journey through the digital garden ✨",
  matchaMsg: "Developer fuel +10! Warm green tea brewed with care 🍵",
  flowerMsg: "You found a tiny secret blossom! The garden smiles upon your curiosity 🌸",
  bugMsg: "404 — The bug ran away into the bamboo grove! 🐛"
};
